const BusinessTypeEnum = Object.freeze({
    GENERAL: 'General',
    RESTAURANT: 'Restaurant',
    RETAIL: 'Retail',
    WHOLESALE: 'Wholesale',
    SALON: 'Salon',
    GROCERY: 'Grocery Store',
    BAKERY: 'Bakery',
    CAFE: 'Cafe',
    SnackStall: 'Snack Stall',
    PHARMACY: 'Pharmacy',
    BOOKSTORE: 'Bookstore',
    HARDWARE: 'Hardware Store',
    CLOTHING: 'Clothing Store',
    JEWELRY: 'Jewelry Store',
    ELECTRONICS: 'Electronics Store',
    FLORIST: 'Florist',
    PET_STORE: 'Pet Store',
    AUTO_REPAIR: 'Auto Repair Shop',
    GYM: 'Gym/Fitness Center',
    DENTIST: 'Dentist',
    OPTICAL: 'Optical Shop',
    LAUNDRY: 'Laundry Service',
    FURNITURE: 'Furniture Store',
    MUSIC_STORE: 'Music Store',
    PHOTO_STUDIO: 'Photo Studio',
    SHOE_STORE: 'Shoe Store',
    GIFT_STORE: 'Gift Store',
    SPORTS_STORE: 'Sports Store',
    ART_GALLERY: 'Art Gallery',
    BARBER_SHOP: 'Barber Shop',
    TATTOO_PARLOR: 'Tattoo Parlor',
    BICYCLE_SHOP: 'Bicycle Shop',
    COMPUTER_REPAIR: 'Computer Repair Service',
    SPORTING_GOODS: 'Sporting Goods Store',
    WINE_SHOP: 'Wine Shop',
    HOME_GOODS: 'Home Goods Store',
    STATIONERY: 'Stationery Store',
    PARTY_SUPPLIES: 'Party Supplies Store',
    AUTO_PARTS: 'Auto Parts Store',
    MEDICAL_CLINIC: 'Medical Clinic',
    ART_SUPPLIES: 'Art Supplies Store',
    WEDDING_PLANNER: 'Wedding Planner',
    SHOE_REPAIR: 'Shoe Repair Shop',
    CATERER: 'Caterer',
    OTHERS : 'Others'
  });
  
  module.exports = BusinessTypeEnum;
  